//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4alleach.MCRecipeEditor.Database.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_4alleach.MCRecipeEditor.Database.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE ItemType (
        ///	[Id]			      uniqueidentifier NOT NULL,
        ///	[Value]   	          nvarchar(50),
        ///
        ///	CONSTRAINT Pk_ItemType PRIMARY KEY ( Id )
        ///);
        ///
        ///CREATE TABLE ModType (
        ///	[Id]			      uniqueidentifier NOT NULL,
        ///    [FullName]            nvarchar(100),
        ///	[ShortName]  	      nvarchar(50),
        ///
        ///	CONSTRAINT Pk_ModType PRIMARY KEY ( Id )
        ///);
        ///
        ///CREATE TABLE ItemPrefix (
        ///	[Id]			      uniqueidentifier NOT NULL,
        ///    [Value]   	          nvarchar(50),
        ///
        ///	CONSTRAINT Pk_ItemPrefix PRIMARY KEY ( Id )
        ///);
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Asset_Create {
            get {
                return ResourceManager.GetString("Asset_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO ItemType ( [Id], [Value] ) 
        ///VALUES ( &apos;8d9f9455-4c58-4c54-afd2-5c64ba1ea6aa&apos;, &apos;Fluid&apos; ),
        ///       ( &apos;276a7692-9213-4cfb-8d0b-e39dc60996d4&apos;, &apos;Block&apos; ),
        ///       ( &apos;0154b8eb-bc89-4967-ab7a-5ed9956fdbaa&apos;, &apos;Entity&apos; );
        ///
        ///INSERT INTO ModType ( [Id], [FullName], [ShortName] ) 
        ///VALUES ( &apos;17c59ca7-f168-4929-929e-f06745abe58d&apos;, &apos;Minecraft&apos;, &apos;minecraft&apos; );
        ///
        ///
        ///INSERT INTO Item ( [Id], [Name], [Description], [ItemTypeId], [ModTypeId] ) 
        ///VALUES ( &apos;de17ef40-6d85-4c12-9d5d-4251bf991de7&apos;, &apos;Air&apos;, &apos;Fill the voi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Asset_Create_DefaultData {
            get {
                return ResourceManager.GetString("Asset_Create_DefaultData", resourceCulture);
            }
        }
    }
}
